### ISSUE TITLE
FakeBlock 2.0.2 not compatible with Paper 1.18.2

### ISSUE THREAD

**Issue by Nutmegan** [toddharrison/BriarCode#20]
Is it possible to make it compatible with Minecraft 1.18.2? Here is the error when running on that version. User is also using FAWE. Is that a problem?

![FakeBlock_Error](https://user-images.githubusercontent.com/9382508/223276207-4bf231b6-1db0-4b6f-a83d-973d511397ae.png)

**Comment by toddharrison** [comment]
This is addressed in 2.0.3 release of fake-block.
